apiVersion: v1
kind: Service
metadata:
  name: notice-service
  labels:
    app: notice-service
spec:
  type: NodePort
  ports:
  - port: 5000
    name: http
    nodePort: 31000
  selector:
    app: notice-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-service
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  selector:
    matchLabels:
      app: notice-service
  template:
    metadata:
      labels:
        app: notice-service
    spec:
      containers:
      - name: notice-service
        image: docker.io/vinho0onguyen/api
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        readinessProbe:
          failureThreshold: 2
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 5"]
