- name: Copy file Deploy to rke-master
  copy:
    src: ~/Ansible/rke2_deploy/api.yml
    dest: /home/vinho0onguyen/rke2_deploy/
    owner: vinho0onguyen


- name: Update version api
  shell: kubectl rollout restart deployment
