- name: get rke2 server script
  get_url:
    url: https://get.rke2.io
    dest: /root/
    mode: "777"

- name: install rke2
  shell: /root/index.html

- name: daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: yes


- name: enable rke2 server
  ansible.builtin.systemd:
     name: rke2-server
     enabled: yes


- name: Start rke2
  ansible.builtin.systemd:
    name: rke2-server
    state: started

- name: Change mode rke2.yml
  shell: chmod 777 -Rf /etc/rancher/rke2/

- name: Add another bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/rke2.sh
    content: 'PATH=$PATH:{{ path_rke2 }}'

- name: Add KUBECONFIG
  copy:
    dest: /etc/profile.d/kubeconfig.sh
    content: 'export KUBECONFIG={{kubeconfig}}'
    
- name: Run script rke2
  shell: source /etc/profile.d/rke2.sh

- name: Run script kubeconfig
  shell: source /etc/profile.d/kubeconfig.sh

- name: Get token
  command: cat /var/lib/rancher/rke2/server/node-token
  register: key

- name: Edit var token
  lineinfile:
    path: /home/vinho0onguyen/main.yml
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
   - 'server: {{inventory_hostname}}'
   - 'token: {{ key.stdout }}'

- name: Fetch token to Ansible server
  ansible.builtin.fetch:
    src: /home/vinho0onguyen/main.yml
    dest: /etc/ansible/roles/rke2-worker/vars/
    flat: yes
