- name: Login repository
  docker_login:
    username: vinho0onguyen
    password: 61f9ac65-fb94-4246-92c6-41c5d7827824

- name: Build images
  shell: DOCKER_BUILDKIT=1 docker build -t api /home/vinho0onguyen/source_code/.

- name: Add tag for image
  shell: docker tag api vinho0onguyen/api

- name: Push image
  shell: docker push vinho0onguyen/api

