- name: install docker
  yum:
    name: docker
    state: latest

- name: Install tool for module docker
  yum:
    name: python-docker
    state: latest

- name: daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start docker
  ansible.builtin.systemd:
    name: docker
    state: started
